service: rs-serverless-image-resizing
provider:
  name: aws
  runtime: rust
  region: ap-southeast-1
  iamRoleStatements:
    -  Effect: "Allow"
       Action:
         - "s3:GetObject"
       Resource: "arn:aws:s3:::image-upload-bucket-staging/*"
    -  Effect: "Allow"
       Action:
         - "s3:PutObject"
       Resource: "arn:aws:s3:::images-to-be-rated-staging/*"
plugins:
  # this adds informs serverless to use
  # the serverless-rust plugin
  - serverless-rust
# creates one artifact for each function
package:
  individually: true
functions:
  test:
    # handler value syntax is `{cargo-package-name}.{bin-name}`
    # or `{cargo-package-name}` for short when you are building a
    # default bin for a given package.
    handler: Rust-serverless-ImageResizing.lambda
    events:
      - http:
          path: /test
          method: GET